name: Dynamic Job Execution Workflow

on:
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Select job to execute'
        required: true
        default: 'test && build'  # Set default value to 'test && build'
        options:
          - deploy
          - 'test && build'  # Use single quotes to denote a single input option

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job_name == 'deploy' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to production
        run: echo "Deploying to production environment"

  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job_name == 'test && build' || github.event.inputs.job_name == 'test' }}
    needs: deploy  # Ensure 'deploy' job completes successfully before running
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: echo "Running tests"

  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job_name == 'test && build' || github.event.inputs.job_name == 'build' }}
    needs: deploy  # Ensure 'deploy' job completes successfully before running
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build application
        run: echo "Building application"
