
name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      company:
        description: 'Company'
        default: ''
        required: true
        type: string

jobs:
  check_company:
    runs-on: ubuntu-latest

    steps:
    - name: Execute Rake task for specific company
      run: RAILS_ENV=dev_it bundle exec rake "am:sqlite[${{ inputs.company }}]" > company-result.zip

    - name: Upload company result
      uses: actions/upload-artifact@v2
      with:
        name: company-result
        path: company-result.txt
