name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      company:
        description: 'Company'
        default: ''
        required: true
        type: string

jobs:
  execute_rake_task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.x

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Execute Rake task for specific company
      run: RAILS_ENV=dev_it bundle exec rake "am:sqlite[${{ github.event.inputs.company }}]"
