name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      country:
        description: 'Country'
        default: ''
        required: true
        type: string

jobs:
  check_country:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create file with countries data
      run: |
        echo "tunis - Données de la Tunisie" > countries.txt
        echo "france - Données de la France" >> countries.txt
        echo "libiya - Données de la Libye" >> countries.txt
        echo "amerique - Données de l'Amérique" >> countries.txt

    - name: Check if country exists
      run: |
        country_input="${{ inputs.country }}"
        if grep -q "^$country_input$" countries.txt; then
          echo "Country $country_input exists"
        else
          echo "Country $country_input does not exist"
        fi
