name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      country:
        description: 'Country'
        default: ''
        required: true
        type: string

jobs:
  check_country:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create file with countries data
      run: |
        echo "tunis " > countries.txt
        echo "france " >> countries.txt
        echo "libiya " >> countries.txt
        echo "amerique " >> countries.txt

    - name: Check if country exists
      id: check_country
      run: |
        country_input="${{ inputs.country }}"
        if grep -q "^$country_input" countries.txt; then
          echo "Country $country_input exists"
          echo "$country_input" > country_result.txt
        else
          echo "Country $country_input does not exist"
          echo "Country $country_input does not exist" > country_result.txt
          exit 1
        fi

    - name: Upload country result
      uses: actions/upload-artifact@v2
      with:
        name: country-result
        path: country_result.txt
