name: Test Workflow


on:
  push:
    branches:
       - main
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Say Hello
        run: echo "merged"

      # Ajoutez ici les étapes pour exécuter votre pipeline de test
