name: Shared Runner Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # You can also specify other operating systems like windows-latest or macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Print a message
        run: echo "This workflow is running on a shared runner."
