name: Shared Runner Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Print a message
        run: echo "This workflow is running on a shared runner."
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and execute shell script
        run: |
          echo "echo 'Hello world from shell script'" > myscript.sh
          chmod +x myscript.sh
          ./myscript.sh
