name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greet
        run: echo "Hello ${{ inputs.name }}"

  deploy:
    runs-on: ubuntu-latest
    needs: greet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy job
        run: |
          echo "Deploying job for ${{ inputs.name }}"
          # Add your deployment steps here
